// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using quizapp_backend.Database;

#nullable disable

namespace quizapp_backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240322081622_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("quizapp_backend.Models.AnswerOptionModels.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("answer_options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "4"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "3"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Paris"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "London"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "George Washington"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Thomas Jefferson"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "1945"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "1918"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "H2O"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "CO2"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Photosynthesis"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Respiration"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Red"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Green"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "White"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Blue"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Yellow"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Black"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Red"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Green"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "White"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Blue"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Yellow"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Black"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Pink"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Red"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Green"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "White"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Blue"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Yellow"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Black"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "Poland"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "France"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Italy"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Germany"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = "Flour, water, yeast, salt"
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Milk, eggs, sugar, flour"
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Butter, sugar, flour, baking powder"
                        },
                        new
                        {
                            Id = 39,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Cornmeal, water, yeast, salt"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "Cream cheese"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "Smoked salmon"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Tomato"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "Avocado"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Peanut butter"
                        });
                });

            modelBuilder.Entity("quizapp_backend.Models.QuestionModels.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer")
                        .HasColumnName("quiz_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Order = 0,
                            QuizId = 1,
                            Text = "What is 2 + 2?"
                        },
                        new
                        {
                            Id = 2,
                            Order = 0,
                            QuizId = 1,
                            Text = "What is the capital of France?"
                        },
                        new
                        {
                            Id = 3,
                            Order = 0,
                            QuizId = 2,
                            Text = "Who was the first president of the United States?"
                        },
                        new
                        {
                            Id = 4,
                            Order = 0,
                            QuizId = 2,
                            Text = "In which year did World War II end?"
                        },
                        new
                        {
                            Id = 5,
                            Order = 0,
                            QuizId = 3,
                            Text = "What is the chemical symbol for water?"
                        },
                        new
                        {
                            Id = 6,
                            Order = 0,
                            QuizId = 3,
                            Text = "What is the process by which plants make their own food?"
                        },
                        new
                        {
                            Id = 7,
                            Order = 0,
                            QuizId = 5,
                            Text = "France"
                        },
                        new
                        {
                            Id = 8,
                            Order = 0,
                            QuizId = 5,
                            Text = "Singapore"
                        },
                        new
                        {
                            Id = 9,
                            Order = 0,
                            QuizId = 5,
                            Text = "Senegal"
                        },
                        new
                        {
                            Id = 10,
                            Order = 0,
                            QuizId = 6,
                            Text = "Where did bagels originate from?"
                        },
                        new
                        {
                            Id = 11,
                            Order = 0,
                            QuizId = 6,
                            Text = "Which of the following are traditional toppings for a bagel?"
                        },
                        new
                        {
                            Id = 12,
                            Order = 0,
                            QuizId = 6,
                            Text = "What are the main ingredients of a bagel?"
                        });
                });

            modelBuilder.Entity("quizapp_backend.Models.QuestionUserAnswerModels.UserAnswer", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("AnswerOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("answer_option_id");

                    b.HasKey("UserId", "AnswerOptionId");

                    b.HasIndex("AnswerOptionId");

                    b.ToTable("user_answers");

                    b.HasData(
                        new
                        {
                            UserId = "e0cbfecd-c1e2-4122-a802-30ca9eb9b2d8",
                            AnswerOptionId = 1
                        },
                        new
                        {
                            UserId = "e0cbfecd-c1e2-4122-a802-30ca9eb9b2d8",
                            AnswerOptionId = 3
                        },
                        new
                        {
                            UserId = "719994b4-0509-4cc3-a089-c7591fb77468",
                            AnswerOptionId = 5
                        },
                        new
                        {
                            UserId = "719994b4-0509-4cc3-a089-c7591fb77468",
                            AnswerOptionId = 7
                        },
                        new
                        {
                            UserId = "b5d56b03-a018-436c-a0c3-ad0b13ac94d7",
                            AnswerOptionId = 9
                        },
                        new
                        {
                            UserId = "b5d56b03-a018-436c-a0c3-ad0b13ac94d7",
                            AnswerOptionId = 11
                        });
                });

            modelBuilder.Entity("quizapp_backend.Models.QuizModels.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 3, 22, 8, 16, 22, 361, DateTimeKind.Utc).AddTicks(3915),
                            Description = "Test your math skills",
                            Title = "Math Quiz",
                            UserId = "e0cbfecd-c1e2-4122-a802-30ca9eb9b2d8"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 3, 21, 8, 16, 22, 361, DateTimeKind.Utc).AddTicks(3915),
                            Description = "Test your knowledge of history",
                            Title = "History Quiz",
                            UserId = "719994b4-0509-4cc3-a089-c7591fb77468"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 3, 20, 8, 16, 22, 361, DateTimeKind.Utc).AddTicks(3915),
                            Description = "Test your understanding of science concepts",
                            Title = "Science Quiz",
                            UserId = "b5d56b03-a018-436c-a0c3-ad0b13ac94d7"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2024, 3, 19, 8, 16, 22, 361, DateTimeKind.Utc).AddTicks(3915),
                            Description = "What colors are present in various countries' flags?",
                            Title = "Country flag colors",
                            UserId = "5a60c9b8-c68b-4779-9f93-b60ffa22c356"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2024, 3, 18, 8, 16, 22, 361, DateTimeKind.Utc).AddTicks(3915),
                            Description = "Test your knowledge about bagels",
                            Title = "Bagel Quiz",
                            UserId = "e0cbfecd-c1e2-4122-a802-30ca9eb9b2d8"
                        });
                });

            modelBuilder.Entity("quizapp_backend.Models.ScoreModels.Attempt", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer")
                        .HasColumnName("quiz_id");

                    b.Property<int>("Correct")
                        .HasColumnType("integer")
                        .HasColumnName("correct");

                    b.Property<int>("HighestPossibleScore")
                        .HasColumnType("integer")
                        .HasColumnName("highest_possible_score");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("Wrong")
                        .HasColumnType("integer")
                        .HasColumnName("wrong");

                    b.HasKey("UserId", "QuizId");

                    b.ToTable("attempt");
                });

            modelBuilder.Entity("quizapp_backend.Models.UserModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = "e0cbfecd-c1e2-4122-a802-30ca9eb9b2d8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0fde883-f381-48c6-8794-cff4f04db2a7",
                            Email = "bob@brainbox.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB@BRAINBOX.COM",
                            NormalizedUserName = "Bob",
                            PasswordHash = "AQAAAAIAAYagAAAAEOS6ud9x/SWrI/BAjgw9pJLbDpojQxiw0YdqiKPyV+UeWfuewGMbHLA+B1OTG0jjQQ==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = "719994b4-0509-4cc3-a089-c7591fb77468",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "79104f43-846d-47d6-a28e-b26f851172df",
                            Email = "bobswife@brainbox.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOBSWIFE@BRAINBOX.COM",
                            NormalizedUserName = "BOBSWIFE",
                            PasswordHash = "AQAAAAIAAYagAAAAEBD0Pnb79C7vR2iPcVttuESkVm2qYBCALXVW0wTEs+PXlvHnsV59x28f2+aTI0iEoQ==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Bob's wife"
                        },
                        new
                        {
                            Id = "b5d56b03-a018-436c-a0c3-ad0b13ac94d7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa7703ec-c0d0-4edf-ac3a-eb001a4f672b",
                            Email = "bobsson@brainbox.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOBSSON@BRAINBOX.COM",
                            NormalizedUserName = "BOBSSON",
                            PasswordHash = "AQAAAAIAAYagAAAAEFLv7kOJbEnGpFmvoSd/xmc428nUHyozB3qFDbBbBHXIansZ42CIGeT0ByuEusQ59A==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Bob's son"
                        },
                        new
                        {
                            Id = "5a60c9b8-c68b-4779-9f93-b60ffa22c356",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "58a6e36e-be54-4d2e-ac52-aeb4cb3e4e30",
                            Email = "stian.k.gaustad@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STIAN.K.GAUSTAD@GMAIL.COM",
                            NormalizedUserName = "SCANDIUMSG",
                            PasswordHash = "AQAAAAIAAYagAAAAEJM8ecUv/l3QeVCTiCc9Bckh8wKCaVv/d1Kda6vfRweQGI7YpbGfzw1hzdAnrL3yLg==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "ScandiumSG"
                        },
                        new
                        {
                            Id = "289daf69-44ca-4ad1-8f2b-9bb4b6fa5482",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "67625a5e-26ad-4d8f-82bd-e01da8c82f2d",
                            Email = "tollov@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TOLLOV@EMAIL.COM",
                            NormalizedUserName = "TOLLOV",
                            PasswordHash = "AQAAAAIAAYagAAAAEC6d9rJJbEyf21KGZFbwvuAiy5GFpiefqoS05XLvVn4d6EbMivBYokd7C7mX0wzjNw==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "tollov"
                        });
                });

            modelBuilder.Entity("quizapp_backend.Models.AnswerOptionModels.AnswerOption", b =>
                {
                    b.HasOne("quizapp_backend.Models.QuestionModels.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("quizapp_backend.Models.QuestionModels.Question", b =>
                {
                    b.HasOne("quizapp_backend.Models.QuizModels.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("quizapp_backend.Models.QuestionUserAnswerModels.UserAnswer", b =>
                {
                    b.HasOne("quizapp_backend.Models.AnswerOptionModels.AnswerOption", "AnswerOption")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quizapp_backend.Models.UserModels.ApplicationUser", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("quizapp_backend.Models.QuizModels.Quiz", b =>
                {
                    b.HasOne("quizapp_backend.Models.UserModels.ApplicationUser", "User")
                        .WithMany("Quizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("quizapp_backend.Models.AnswerOptionModels.AnswerOption", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("quizapp_backend.Models.QuestionModels.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("quizapp_backend.Models.QuizModels.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("quizapp_backend.Models.UserModels.ApplicationUser", b =>
                {
                    b.Navigation("Quizzes");

                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
